services:
  app:
    build: .
    container_name: finanse-master-php-container
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /var/www/html/
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:8.4.5
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql-finance-master:/var/lib/mysql
volumes:
  mysql-finance-master:
